swagger: '2.0'
info:
  title: Your API
  description: Your API description
  version: v1
host: 127.0.0.1:8000
schemes:
- http
basePath: /api/v1
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  Basic:
    type: basic
security:
- Basic: []
paths:
  /login/:
    post:
      operationId: login_create
      description: 'Вход пользователя.'
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/UserLogin'
      responses:
        '200':
          description: 'OK'
          schema:
            $ref: '#/definitions/UserLogin'
        '401':
          description: 'UNAUTHORIZED'
      tags:
      - login

  /register/:
    post:
      operationId: register_create
      description: 'Регистрация пользователя.'
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/UserRegistration'
      responses:
        '201':
          description: 'CREATED'
          schema:
            $ref: '#/definitions/UserRegistration'
        '400':
          description: 'BAD REQUEST'
      tags:
      - register

  /profileupdate/:
    put:
      operationId: profile_update
      description: 'Обновление профиля пользователя.'
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/UserProfileUpdate'
      responses:
        '200':
          description: 'Профиль успешно обновлен.'
          schema:
            $ref: '#/definitions/UserProfileUpdate'
        '400':
          description: 'Неверные данные.'
      tags:
      - profile

  /admins-list/:
    get:
      operationId: admins_list
      description: 'Получение списка администраторов.'
      responses:
        '200':
          description: 'Список администраторов.'
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
      tags:
      - admins

  /managers-list/:
    get:
      operationId: managers_list
      description: 'Получение списка менеджеров.'
      responses:
        '200':
          description: 'Список менеджеров.'
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
      tags:
      - managers

  /change-pass/:
    post:
      operationId: change_password
      description: 'Изменение пароля пользователя.'
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/ChangePassword'
      responses:
        '200':
          description: 'Пароль успешно изменен.'
        '400':
          description: 'Неверные данные.'
          schema:
            type: object
            properties:
              new_password_confirm:
                type: string
                example: "Пароли не совпадают."
      tags:
      - password

definitions:
  UserLogin:
    required:
    - username
    - password
    type: object
    properties:
      username:
        title: Username
        type: string
        minLength: 1
      password:
        title: Password
        type: string
        minLength: 1
      role:
        title: Role
        type: string
        readOnly: true

  UserRegistration:
    required:
    - username
    - password
    - password_confirm
    - email
    - role
    type: object
    properties:
      username:
        title: Username
        description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
        type: string
        pattern: ^[\w.@+-]+$
        maxLength: 150
        minLength: 1
      password:
        title: Password
        type: string
        minLength: 1
      password_confirm:
        title: Password confirm
        type: string
        minLength: 1
      email:
        title: Email
        type: string
        format: email
        maxLength: 254
        minLength: 1
      role:
        title: Role
        type: integer

  UserProfileUpdate:
    required:
    - username
    - email
    type: object
    properties:
      username:
        title: Username
        type: string
        minLength: 1
      first_name:
        title: First Name
        type: string
        required: false
      middle_name:
        title: Middle Name
        type: string
        required: false
      last_name:
        title: Last Name
        type: string
        required: false
      email:
        title: Email
        type: string
        format: email
        maxLength: 254
        minLength: 1
      tg_nickname:
        title: Telegram Nickname
        type: string
        required: false

  ChangePassword:
    required:
    - old_password
    - new_password
    - new_password_confirm
    type: object
    properties:
      old_password:
        title: Old Password
        type: string
        minLength: 1
      new_password:
        title: New Password
        type: string
        minLength: 1
        description: 'Пароль должен соответствовать требованиям валидации.'
      new_password_confirm:
        title: Confirm New Password
        type: string
        minLength: 1

  User:
    type: object
    properties:
      id:
        type: integer
      username:
        type: string
      email:
        type: string
      role:
        type: string
